workspace:
  base: /go
  path: src/github.com/hill-daniel/drone-lambda-plugin

pipeline:
  build:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - go get ./...
      - go build main.go

  docker:
    image: plugins/docker
    repo: danielhill/drone-lambda-plugin
    tags: latest
    secrets: [ docker_username, docker_password, docker_email ]
